import {useEffect,useState} from 'react'
import type {FeishuSettings as Settings} from '../../../electron/sop/feishu'
import type {CliDiscovery} from '../../../electron/sop/feishu-setup'
export function FeishuSettings(){
  const [value,setValue]=useState<Settings>(),[discovery,setDiscovery]=useState<CliDiscovery>(),[message,setMessage]=useState('正在自动检测…'),[busy,setBusy]=useState(false),[auth,setAuth]=useState<{url:string;qr:string;init:boolean}>()
  const accept=(d:CliDiscovery)=>{setDiscovery(d);setValue(d.settings);return d}
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  useEffect(()=>{void run(async()=>{const d=accept(await window.taSop.feishuDiscover());setMessage(d.installed?'已找到本机飞书 CLI，可直接复用已有账号。':'未安装飞书 CLI，点击下方按钮自动安装。')})},[])
  const configure=()=>void run(async()=>{const d=accept(await window.taSop.feishuInstall());await window.taSop.feishuSave({...d.settings,parentToken:value?.parentToken??d.settings.parentToken});if(d.profiles.length){const r=await window.taSop.feishuStatus(d.settings);setMessage('自动配置完成。'+r.message)}else{const r=await window.taSop.feishuInitialize();setAuth({...r,init:true});setMessage('请扫码或打开飞书网页完成首次配置。')}})
  return <section className="sop-feishu-settings"><h2>飞书云文档</h2><p>自动检测本机飞书 CLI 和已有账号。首次使用可一键安装，再由飞书官方网页完成授权。</p><div className="sop-cli-status"><strong>{discovery?.installed?'已检测到飞书 CLI':'尚未连接飞书'}</strong><small>{discovery?.version}</small></div>
    <div className="sop-actions"><button className="primary" disabled={busy} onClick={configure}>{discovery?.installed?'一键配置':'一键安装并配置'}</button><button disabled={busy} onClick={()=>void run(async()=>{accept(await window.taSop.feishuDiscover());setMessage('检测完成。')})}>重新检测</button></div>
    {value&&<fieldset disabled={busy}><label>飞书账号<select aria-label="飞书账号" value={value.profile} onChange={e=>setValue({...value,profile:e.target.value})}>{!discovery?.profiles.length&&<option value="">尚未配置账号</option>}{discovery?.profiles.map(p=><option key={p.name} value={p.name}>{p.user?p.user+' · ':''}{p.name}{p.active?'（当前账号）':''}</option>)}</select></label><label>保存位置<input aria-label="飞书目标位置" value={value.parentToken} placeholder="粘贴文件夹或知识库链接，可留空" onChange={e=>setValue({...value,parentToken:e.target.value})}/></label><small>留空保存到当前账号的云空间。发布时会创建新文档。</small><div className="sop-actions"><button disabled={!discovery?.installed} onClick={()=>void run(async()=>{setValue(await window.taSop.feishuSave(value));setMessage('飞书配置已保存。')})}>保存飞书配置</button><button disabled={!discovery?.installed} onClick={()=>void run(async()=>setMessage((await window.taSop.feishuStatus(value)).message))}>测试飞书连接</button><button disabled={!discovery?.installed||!discovery.profiles.length} onClick={()=>void run(async()=>{setAuth({...await window.taSop.feishuLogin(value),init:false});setMessage('请用飞书扫码授权，完成后点击“已完成授权”。')})}>登录 / 重新授权</button></div>
    <details><summary>高级设置</summary><label>CLI 程序<input aria-label="飞书 CLI 路径" value={value.executable} onChange={e=>setValue({...value,executable:e.target.value})}/><button onClick={()=>void run(async()=>{const file=await window.taSop.feishuChoose();if(file)setValue({...value,executable:file})})}>选择程序</button></label><small>通常无需修改。已有配置和密钥由飞书 CLI 管理。</small></details></fieldset>}
    {auth&&<div className="sop-cli-auth"><img src={auth.qr} alt="飞书官方授权二维码"/><p>扫码或在浏览器中打开链接，完成飞书{auth.init?'应用配置':'账号授权'}。</p><a href={auth.url} onClick={e=>{e.preventDefault();void window.taSop.feishuOpenAuth().catch(e=>setMessage(e.message))}}>打开飞书授权页面</a><button disabled={busy} onClick={()=>void run(async()=>{const d=accept(await (auth.init?window.taSop.feishuInitializeComplete():window.taSop.feishuLoginComplete()));setAuth(undefined);setMessage(auth.init?'应用配置完成，请点击“登录 / 重新授权”完成云文档授权。':(await window.taSop.feishuStatus(d.settings)).message)})}>已完成授权</button></div>}
    <p role="status">{busy?'正在处理，请稍候…':message}</p></section>
}
