import { useEffect, useRef, useState, type PointerEvent } from 'react'
import { media, type VideoProject } from '../video/bridge'
import { timestamp } from '../../../electron/sop/model'
import type { SopDocument, SopImage, SopStep, SopVersion } from './bridge'
import './sop.css'

const api=()=>window.taSop
const newStep=():SopStep=>({id:crypto.randomUUID(),title:'新步骤',body:'',expected:'',note:'',time:null,images:[]})
export function SopWorkspace({project,onExit,onVideo,onError}:{project:VideoProject;onExit:()=>void;onVideo:()=>void;onError:(s:string)=>void}) {
  const [doc,setDoc]=useState<SopDocument>(),latest=useRef<SopDocument|undefined>(undefined),dirty=useRef(false),edits=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),queue=useRef(Promise.resolve())
  const [saved,setSaved]=useState(true),[busy,setBusy]=useState(false),busyRef=useRef(false),[status,setStatus]=useState(''),[selected,setSelected]=useState(''),[time,setTime]=useState(0),[tab,setTab]=useState<'source'|'chat'>('source'),[prompt,setPrompt]=useState(''),[versions,setVersions]=useState<SopVersion[]>(),[options,setOptions]=useState(false),[format,setFormat]=useState('docx'),[asr,setAsr]=useState('whisper-1'),[editImage,setEditImage]=useState<{step:string;image:SopImage}>()
  const video=useRef<HTMLVideoElement>(null),mic=useRef<HTMLAudioElement>(null),system=useRef<HTMLAudioElement>(null),alive=useRef(true),chatEnd=useRef<HTMLDivElement>(null)
  const accept=(d:SopDocument)=>{latest.current=d;dirty.current=false;setSaved(true);setDoc(d)}
  const change=(d:SopDocument)=>{if(busyRef.current)return;latest.current=d;dirty.current=true;edits.current++;setDoc(d);setSaved(false);clearTimeout(timer.current);timer.current=setTimeout(()=>void flush().catch(e=>onError(e.message)),600)}
  const flush=()=>{clearTimeout(timer.current);const run=queue.current.catch(()=>{}).then(async()=>{while(dirty.current&&latest.current){const n=edits.current;const result=await api().save(latest.current);if(n===edits.current){dirty.current=false;latest.current=result;if(alive.current){setDoc(result);setSaved(true)}}else{latest.current={...latest.current,revision:result.revision};if(alive.current)setDoc(latest.current)}}});queue.current=run;return run}
  const work=async(fn:()=>Promise<SopDocument|undefined|void>)=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);video.current?.pause();try{await flush();const d=await fn();if(d)accept(d)}catch(e){onError(e instanceof Error?e.message:String(e))}finally{busyRef.current=false;if(alive.current){setBusy(false);setStatus('')}}}
  useEffect(()=>{alive.current=true;void api().get(project.id).then(accept).catch(e=>onError(e.message));const off=api().onProgress(p=>{if(p.projectId===project.id)setStatus(p.message+(p.total>1?` ${Math.round(p.current/p.total*100)}%`:''))});const close=window.taVideo.onClosing(()=>{if(busyRef.current){onError('正在处理文档，请等待完成或先取消。');return}void flush().then(()=>window.taVideo.closeReady()).catch(e=>onError(e.message))});return()=>{alive.current=false;off();close();clearTimeout(timer.current)}},[project.id])
  useEffect(()=>{chatEnd.current?.scrollIntoView({block:'nearest'})},[doc?.chat.length])
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();void flush().catch(e=>onError(e.message))}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[])
  const patch=(id:string,value:Partial<SopStep>)=>{if(latest.current)change({...latest.current,steps:latest.current.steps.map(s=>s.id===id?{...s,...value}:s)})}
  const focus=(id:string)=>{setSelected(id);document.getElementById('sop-step-'+id)?.scrollIntoView({behavior:'smooth',block:'start'})}
  const seek=(t:number)=>{setTab('source');setTime(t);if(video.current){video.current.currentTime=t/1000;video.current.pause()}for(const a of [mic.current,system.current])if(a){a.currentTime=t/1000;a.pause()}}
  const sync=()=>{const v=video.current;if(!v)return;setTime(Math.min(project.duration,v.currentTime*1000));for(const a of [mic.current,system.current])if(a){a.volume=v.volume;a.muted=v.muted;if(Math.abs(a.currentTime-v.currentTime)>.12)a.currentTime=v.currentTime;if(v.paused)a.pause();else if(a.paused)void a.play().catch(()=>{})}}
  const addStep=(after=selected)=>{const d=latest.current;if(!d)return;const s=newStep(),steps=[...d.steps],n=steps.findIndex(s=>s.id===after);steps.splice(n<0?steps.length:n+1,0,s);change({...d,steps});setSelected(s.id)}
  const addImage=(kind:'frame'|'upload'|'paste',target=selected,replace?:string)=>work(async()=>{const d=structuredClone(latest.current!);let s=d.steps.find(s=>s.id===target);const image=kind==='frame'?await api().frame(project.id,time):await api().image(project.id,kind==='paste');if(!image)return
    if(!s){s=newStep();s.title='补充操作';d.steps.push(s);setSelected(s.id)}
    if(replace)s.images=s.images.map(i=>i.id===replace?image:i);else s.images.push(image)
    if(s.time===null)s.time=image.time
    return api().save(d)
  })
  const move=(id:string,delta:number)=>{const d=latest.current!,steps=[...d.steps],n=steps.findIndex(s=>s.id===id),to=n+delta;if(to<0||to>=steps.length)return;[steps[n],steps[to]]=[steps[to],steps[n]];change({...d,steps})}
  if(!doc)return <main className="sop-loading">正在打开 SOP 工作区…</main>
  return <main className="sop-workspace" aria-busy={busy}>
    <div className="sop-toolbar"><button disabled={busy} onClick={()=>void work(async()=>{onExit()})}>← 视频库</button><div className="sop-doc-label"><b>SOP 文档</b><span>{busy?status||'正在处理…':saved?'已保存到本机':'正在保存…'}</span></div><button disabled={busy} onClick={()=>setOptions(!options)}>生成设置</button><button disabled={busy} onClick={()=>void work(async()=>{setVersions(await api().versions(project.id))})}>历史版本</button><button disabled={busy} onClick={()=>void work(async()=>{onVideo()})}>视频剪辑</button><select aria-label="SOP 导出格式" value={format} onChange={e=>setFormat(e.target.value)}>{['docx','pdf','html','md'].map(f=><option key={f} value={f}>{({docx:'Word',pdf:'PDF',html:'网页',md:'Markdown'})[f]}</option>)}</select><button className="primary" disabled={busy||!doc.steps.length} onClick={()=>void work(async()=>{const file=await api().export(project.id,format);if(file)onError('SOP 已导出：'+file)})}>导出 SOP</button></div>
    {busy&&<div className="sop-progress" role="status"><span>{status||'正在处理，请稍候…'}</span><button onClick={()=>void api().cancel(project.id)}>取消 AI 处理</button></div>}
    {options&&<section className="sop-options"><div><label>给谁看<input disabled={busy} value={doc.audience} maxLength={300} onChange={e=>change({...doc,audience:e.target.value})}/></label><label>说明细度<select disabled={busy} value={doc.detail} onChange={e=>change({...doc,detail:e.target.value as SopDocument['detail']})}><option value="quick">精简：保留关键路径</option><option value="standard">标准：步骤、配图和完成状态</option><option value="detailed">详细：适合第一次操作</option></select></label></div><label>作者要求<textarea disabled={busy} value={doc.instructions} maxLength={8000} onChange={e=>change({...doc,instructions:e.target.value})} placeholder="例如：保留输入的提示词；把容易出错的地方单独说明。"/></label><p>生成和对话会将选取的画面、字幕及文档发送给主窗口设置中的 AI 服务。支持最长 30 分钟的视频。长录屏建议分成独立任务。</p><div className="sop-actions"><button disabled={busy} onClick={()=>void work(async()=>api().subtitles(project.id))}>导入 SRT / VTT</button><input aria-label="语音模型" value={asr} onChange={e=>setAsr(e.target.value)} placeholder="语音识别模型"/><button disabled={busy||(!project.hasMic&&!project.hasSystem)} onClick={()=>void work(()=>api().transcribe(project.id,asr))}>转写讲解录音</button><span>{doc.transcript.length?`已载入 ${doc.transcript.length} 段讲解`:'可先转写讲解，再生成 SOP'}</span></div>{doc.transcript.length>0&&<details><summary>查看与修正讲解文字</summary>{doc.transcript.map((t,i)=><label key={i}><button onClick={()=>seek(t.start)}>{timestamp(t.start)}</button><textarea disabled={busy} value={t.text} onChange={e=>change({...doc,transcript:doc.transcript.map((v,n)=>n===i?{...v,text:e.target.value}:v)})}/></label>)}</details>}</section>}
    <div className="sop-columns">
      <aside className="sop-outline"><div className="sop-section-label">操作目录 <span>{doc.steps.length}</span></div><button className="sop-generate" disabled={busy} onClick={()=>void work(()=>api().generate(project.id))}>{doc.steps.length?'重新生成 SOP':'生成 SOP'}</button><small>{doc.steps.length?'重新生成前会保留历史版本':'根据画面与讲解生成步骤'}</small><div className="sop-step-links">{doc.steps.map((s,i)=><button key={s.id} className={selected===s.id?'active':''} onClick={()=>focus(s.id)}><span>{String(i+1).padStart(2,'0')}</span><b>{s.title||'未命名步骤'}</b></button>)}</div><button disabled={busy} onClick={()=>addStep()}>＋ 添加步骤</button></aside>
      <article className="sop-document"><div className="sop-document-heading"><span className="sop-kicker">操作指引 / STANDARD OPERATING PROCEDURE</span><input className="sop-title" aria-label="SOP 标题" disabled={busy} maxLength={200} value={doc.title} onChange={e=>change({...doc,title:e.target.value})}/><textarea className="sop-description" aria-label="SOP 简介" disabled={busy} value={doc.description} maxLength={8000} onChange={e=>change({...doc,description:e.target.value})} placeholder="这篇指引能帮助读者完成什么？需要提前准备什么？"/><div className="sop-document-meta">{doc.audience} <span>·</span> {doc.steps.length} 个步骤 <span>·</span> 原视频 {timestamp(project.duration)}</div></div>
        {!doc.steps.length&&<div className="sop-empty"><span className="sop-empty-icon">拓</span><h2>把一次演示，整理成可照做的指引。</h2><p>点击「生成 SOP」，AI 会挑选画面并整理步骤。生成后可以直接修改文字，或用对话补充遗漏的截图。</p><button className="primary" disabled={busy} onClick={()=>void work(()=>api().generate(project.id))}>生成第一版 SOP</button><button disabled={busy} onClick={()=>addStep()}>从空白步骤开始</button></div>}
        {doc.steps.map((s,n)=><section className={'sop-step '+(selected===s.id?'selected':'')} key={s.id} id={'sop-step-'+s.id} onClick={()=>setSelected(s.id)}><div className="sop-step-top"><span className="sop-number">{String(n+1).padStart(2,'0')}</span><input aria-label={`步骤 ${n+1} 标题`} disabled={busy} value={s.title} maxLength={300} onChange={e=>patch(s.id,{title:e.target.value})}/><div className="sop-reorder"><button disabled={busy||n===0} title="上移步骤" onClick={()=>move(s.id,-1)}>↑</button><button disabled={busy||n===doc.steps.length-1} title="下移步骤" onClick={()=>move(s.id,1)}>↓</button><button disabled={busy} title="移除步骤，可从历史版本恢复" onClick={()=>change({...doc,steps:doc.steps.filter(v=>v.id!==s.id)})}>×</button></div></div><textarea className="sop-body" aria-label={`步骤 ${n+1} 说明`} rows={Math.max(3,Math.min(12,s.body.split('\n').length+1))} disabled={busy} value={s.body} maxLength={12000} onChange={e=>patch(s.id,{body:e.target.value})} placeholder="描述要点击哪里、输入什么，以及为什么这样做。"/>
          {s.images.map(im=><figure className="sop-image" key={im.id}><img src={media(project.id,im.file)} alt={im.caption||s.title} onDoubleClick={()=>setEditImage({step:s.id,image:im})}/><figcaption><input aria-label="配图说明" disabled={busy} value={im.caption} maxLength={1000} placeholder="添加配图说明" onChange={e=>patch(s.id,{images:s.images.map(i=>i.id===im.id?{...i,caption:e.target.value}:i)})}/><button disabled={im.time===null} title="跳到原视频" onClick={()=>im.time!==null&&seek(im.time)}>{im.time===null?'补充截图':timestamp(im.time)}</button></figcaption><div className="sop-image-tools"><button disabled={busy} onClick={()=>setEditImage({step:s.id,image:im})}>裁切 / 高亮 / 遮挡</button><button disabled={busy} onClick={()=>void addImage('frame',s.id,im.id)}>用当前帧替换</button><button disabled={busy} onClick={()=>patch(s.id,{images:s.images.filter(i=>i.id!==im.id)})}>移除配图</button></div></figure>)}
          <div className="sop-step-notes"><label>完成后<textarea disabled={busy} value={s.expected} maxLength={4000} onChange={e=>patch(s.id,{expected:e.target.value})} placeholder="读者如何确认这一步做对了？"/></label><label>提示<textarea disabled={busy} value={s.note} maxLength={4000} onChange={e=>patch(s.id,{note:e.target.value})} placeholder="必要的注意事项，或需要核对的内容"/></label></div><div className="sop-actions sop-step-footer"><button disabled={busy||s.images.length>=12} onClick={()=>void addImage('frame',s.id)}>＋ 当前视频帧</button><button disabled={busy||s.images.length>=12} onClick={()=>void addImage('upload',s.id)}>添加图片</button><button disabled={busy||s.images.length>=12} onClick={()=>void addImage('paste',s.id)}>粘贴截图</button><button disabled={busy} onClick={()=>{setSelected(s.id);setTab('chat');setPrompt('请修改当前步骤：')}}>让 AI 修改</button></div></section>)}
      </article>
      <aside className="sop-side"><div className="sop-tabs"><button className={tab==='source'?'chosen':''} onClick={()=>setTab('source')}>来源视频</button><button className={tab==='chat'?'chosen':''} onClick={()=>setTab('chat')}>AI 编辑</button></div><div className="sop-source" hidden={tab!=='source'}><video ref={video} controls preload="metadata" src={media(project.id,'screen.mp4')} onTimeUpdate={sync} onPlay={sync} onPause={sync} onSeeked={sync} onVolumeChange={sync}/>{project.hasMic&&<audio ref={mic} src={media(project.id,'mic.wav')}/>} {project.hasSystem&&<audio ref={system} src={media(project.id,'system.wav')}/>}<div className="sop-seek"><button onClick={()=>seek(Math.max(0,time-1000/30))}>‹ 一帧</button><input aria-label="原视频秒数" type="number" min={0} max={project.duration/1000} step={.1} value={Number((time/1000).toFixed(2))} onChange={e=>seek(Math.max(0,Math.min(project.duration,Number(e.target.value)*1000)))}/><span>秒</span><button onClick={()=>seek(Math.min(project.duration,time+1000/30))}>一帧 ›</button></div><button className="sop-wide" disabled={busy} onClick={()=>void addImage('frame')}>截取当前帧，插入{selected?'选中步骤':'新步骤'}</button><p>选中左侧步骤，再定位视频时间即可补图。文档配图上的时间可以跳回原视频。</p><div className="sop-source-info"><b>{project.title}</b><span>{project.width} × {project.height} · {timestamp(project.duration)}</span></div><button className="sop-wide" disabled={busy} onClick={()=>{setTab('chat');setPrompt('请帮我找到遗漏的操作截图，补到当前步骤：')}}>让 AI 帮我找遗漏画面</button></div>
      <div className="sop-chat" hidden={tab!=='chat'}><p className="sop-chat-context">{selected?`当前步骤：${doc.steps.find(s=>s.id===selected)?.title??'已移除'}`:'当前范围：整篇 SOP'}</p><div className="sop-messages">{!doc.chat.length&&<div className="sop-chat-welcome"><h3>像和编辑沟通一样修改。</h3><p>可以调整说明、拆分或合并步骤，也可以让我从视频里寻找缺图。</p>{['把说明改得更适合新手，保留关键输入','帮我检查步骤是否有重复，整理结构','在当前步骤补充操作完成后的截图'].map(s=><button key={s} onClick={()=>setPrompt(s)}>{s}</button>)}</div>}{doc.chat.map((m,i)=><div key={i} className={'sop-message '+m.role}><small>{m.role==='user'?'你':'AI 编辑'}</small><p>{m.text}</p></div>)}<div ref={chatEnd}/></div><form onSubmit={e=>{e.preventDefault();const message=prompt;setPrompt('');void work(()=>api().chat(project.id,message,selected||undefined,time))}}><textarea aria-label="AI 修改要求" disabled={busy} value={prompt} maxLength={8000} onChange={e=>setPrompt(e.target.value)} placeholder="例如：第 3 步缺了选择模型的截图，请从视频中补上，并补充说明。"/><button className="primary" disabled={busy||!prompt.trim()}>发送修改要求</button><small>修改可从历史版本恢复 · 使用已配置的 AI 服务</small></form></div></aside>
    </div>
    {versions&&<div className="sop-modal-backdrop"><section className="sop-modal" role="dialog" aria-label="历史版本"><div className="sop-modal-head"><h2>历史版本</h2><button onClick={()=>setVersions(undefined)}>关闭</button></div><p>恢复会创建新版本，当前文档仍会保留。</p>{versions.length?versions.map(v=><div className="sop-version" key={v.revision}><div><b>版本 {v.revision} · {v.reason}</b><small>{new Date(v.updatedAt).toLocaleString()} · {v.title}</small></div><button disabled={busy} onClick={()=>void work(async()=>{const d=await api().restore(project.id,v.revision);setVersions(undefined);return d})}>恢复</button></div>):<p>还没有历史版本。</p>}</section></div>}
    {editImage&&<ImageEditor id={project.id} image={editImage.image} busy={busy} onClose={()=>setEditImage(undefined)} onApply={(mode,rect)=>void work(async()=>{const next=await api().transform(project.id,editImage.image,mode,rect),d=structuredClone(latest.current!),s=d.steps.find(s=>s.id===editImage.step)!;s.images=s.images.map(i=>i.id===next.id?next:i);const result=await api().save(d);setEditImage(undefined);return result})}/>}
  </main>
}

function ImageEditor({id,image,busy,onClose,onApply}:{id:string;image:SopImage;busy:boolean;onClose:()=>void;onApply:(mode:string,rect:{x:number;y:number;width:number;height:number})=>void}) {
  const [mode,setMode]=useState('highlight'),[rect,setRect]=useState({x:0,y:0,width:0,height:0}),start=useRef<{x:number;y:number}|undefined>(undefined)
  const point=(e:PointerEvent)=>{const r=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
  return <div className="sop-modal-backdrop"><section className="sop-modal sop-image-modal" role="dialog" aria-label="编辑配图"><div className="sop-modal-head"><h2>编辑这张配图</h2><button disabled={busy} onClick={onClose}>关闭</button></div><div className="sop-actions">{(['highlight','crop','blur'] as const).map(m=><button key={m} disabled={busy} className={mode===m?'chosen':''} onClick={()=>setMode(m)}>{({highlight:'突出重点',crop:'裁切区域',blur:'模糊遮挡'})[m]}</button>)}{image.original&&<button disabled={busy} onClick={()=>onApply('restore',rect)}>恢复原图</button>}<button className="primary" disabled={busy||rect.width<.005||rect.height<.005} onClick={()=>onApply(mode,rect)}>应用到配图</button></div><p>在图上拖出区域。效果只应用于这张文档配图，原图保留，可恢复。</p><div className="sop-image-canvas" onPointerDown={e=>{if(busy)return;start.current=point(e);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!start.current)return;const p=point(e),a=start.current;setRect({x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),width:Math.abs(p.x-a.x),height:Math.abs(p.y-a.y)})}} onPointerUp={()=>{start.current=undefined}}><img draggable={false} src={media(id,image.file)} alt="待编辑配图"/><span style={{left:rect.x*100+'%',top:rect.y*100+'%',width:rect.width*100+'%',height:rect.height*100+'%'}}/></div></section></div>
}
