import {useEffect,useRef,useState,type CSSProperties,type PointerEvent} from 'react'
import {migrateTimeline,clipDuration,clipEnd,clipSourceTime,timelineDuration,activeClip,keyAt,makeClip,replaceLinked,removeLinked,splitLinked,resizeSpeed,type TimelineClip,type TimelineTrack,type TrackKind,type Keyframe} from '../../../electron/video/timeline'
import {clamp,markSvg,type VideoProject,type MarkTool} from '../../../electron/video/model'
import {media,clockText} from './bridge'
import './timeline.css'
const uid=()=>crypto.randomUUID()
type Project=VideoProject&{timeline:ReturnType<typeof migrateTimeline>}
export function TimelineEditor({initial,onError,onExit}:{initial:VideoProject;onError:(s:string)=>void;onExit?:()=>void}){
  const [p,setP]=useState<Project>(()=>({...initial,timeline:migrateTimeline(initial)})),latest=useRef(p),dirty=useRef(false),revision=useRef(0),queue=useRef(Promise.resolve()),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined)
  const [time,setTime]=useState(0),clock=useRef(0),[playing,setPlaying]=useState(false),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),busyRef=useRef(false),[saved,setSaved]=useState(true),[progress,setProgress]=useState(''),[height,setHeight]=useState(1080),[px,setPx]=useState(40)
  const undo=useRef<Project[]>([]),redo=useRef<Project[]>([]),[tool,setTool]=useState<MarkTool|'region'|'select'>('select'),[color,setColor]=useState('#FF4D37'),[text,setText]=useState('重点'),[draft,setDraft]=useState<{x:number;y:number;width:number;height:number}>(),stage=useRef<HTMLDivElement>(null)
  const region=useRef<{x:number;y:number}|undefined>(undefined),drag=useRef<{before:Project;clip:TimelineClip;track:string;x:number;mode:'move'|'speed'|'trim';next?:Project}|undefined>(undefined),[dragging,setDragging]=useState(false)
  const duration=timelineDuration(p.timeline),track=p.timeline.tracks.find(t=>t.clips.some(c=>c.id===selected)),clip=track?.clips.find(c=>c.id===selected)
  const update=(next:Project,record=true,before=latest.current)=>{if(busyRef.current)return;if(record){undo.current.push(structuredClone(before));if(undo.current.length>100)undo.current.shift();redo.current=[]}latest.current=next;setP(next);dirty.current=true;revision.current++;setSaved(false);clearTimeout(timer.current);timer.current=setTimeout(()=>void flush().catch(e=>onError(e.message)),600)}
  const flush=()=>{clearTimeout(timer.current);queue.current=queue.current.catch(()=>{}).then(async()=>{while(dirty.current){const n=revision.current,result=await window.taVideo.save(latest.current.id,latest.current);if(n===revision.current){dirty.current=false;latest.current={...result,timeline:result.timeline!};setP(latest.current);setSaved(true)}else latest.current={...latest.current,revision:result.revision,assets:result.assets}}});return queue.current}
  const work=async(fn:()=>Promise<void>)=>{if(busyRef.current)return;setPlaying(false);busyRef.current=true;setBusy(true);try{await flush();await fn()}catch(e){onError(e instanceof Error?e.message:String(e))}finally{busyRef.current=false;setBusy(false);setProgress('')}}
  const travel=(forward=false)=>{if(busyRef.current)return;const from=forward?redo.current:undo.current,to=forward?undo.current:redo.current,next=from.pop();if(next){to.push(latest.current);update({...next,assets:latest.current.assets},false)}}
  const seek=(t:number)=>{setPlaying(false);clock.current=clamp(t,0,duration);setTime(clock.current)}
  useEffect(()=>{const off=window.taVideo.onClosing(()=>{if(busyRef.current){onError('正在导出或导入，请等待完成或取消导出。');return}void flush().then(()=>window.taVideo.closeReady()).catch(e=>onError(e.message))});const exportOff=window.taVideo.onExport(e=>setProgress(e.message+' '+Math.round(e.progress*100)+'%'));return()=>{off();exportOff();clearTimeout(timer.current)}},[])
  useEffect(()=>{if(!playing)return;let raf=0,last=performance.now();const tick=(now:number)=>{const next=clock.current+now-last;last=now;clock.current=Math.min(next,timelineDuration(latest.current.timeline));setTime(clock.current);if(next>=timelineDuration(latest.current.timeline)){setPlaying(false);return}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[playing])
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.isComposing||(e.target as HTMLElement).matches('input,textarea,select'))return;if((e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();travel(e.shiftKey||e.key.toLowerCase()==='y')}else if(e.code==='Space'){e.preventDefault();setPlaying(v=>!v)}else if(e.key==='Delete')remove();else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='b'){e.preventDefault();split()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[selected,p])
  const replace=(c:TimelineClip)=>update({...latest.current,timeline:replaceLinked(latest.current.timeline,c)})
  const remove=()=>{if(!clip)return;const next={...latest.current,timeline:removeLinked(latest.current.timeline,clip)};if(!next.timeline.tracks.some(t=>t.kind==='video'&&t.clips.length)){onError('至少保留一个视频片段。');return}update(next);setSelected('')}
  const split=()=>{if(!clip||!track)return;try{const next=splitLinked(p.timeline,clip,time,uid);update({...p,timeline:next});setSelected(next.tracks.find(t=>t.id===track.id)!.clips.find(c=>c.start===time)?.id??clip.id)}catch(e){onError((e as Error).message)}}
  const addTrack=(kind:TrackKind)=>{const id=uid();update({...p,timeline:{...p.timeline,tracks:[...p.timeline.tracks,{id,kind,name:({video:'视频',audio:'音频',mark:'标记',zoom:'区域缩放'})[kind]+'轨道',muted:false,clips:[]}]}})}
  const addClip=(kind:TrackKind,c:TimelineClip)=>{const next=structuredClone(latest.current),target=next.timeline.tracks.find(t=>t.kind===kind&&t.id===track?.id)??next.timeline.tracks.find(t=>t.kind===kind);if(target)target.clips.push(c);else next.timeline.tracks.push({id:uid(),kind,name:kind==='zoom'?'区域缩放':'标记',muted:false,clips:[c]});update(next);setSelected(c.id)}
  const importMedia=(kind:'video'|'audio')=>void work(async()=>{const result=await window.taVideo.importMedia(p.id,kind);if(!result)return;const next={...latest.current,assets:result.project.assets};const target=next.timeline.tracks.find(t=>t.kind===kind&&t.id===track?.id);const c=makeClip(uid(),result.asset.name,result.asset.file,result.asset.duration,time);if(kind==='video'){c.rect={x:.65,y:.05,width:.3,height:.3}}const tracks=next.timeline.tracks.map(t=>t.id===target?.id?{...t,clips:[...t.clips,c]}:t);if(!target)tracks.push({id:uid(),name:kind==='video'?'补充视频':'补充音频',kind,muted:false,clips:[c]});busyRef.current=false;update({...next,timeline:{version:1,tracks}});busyRef.current=true;setSelected(c.id)})
  const camera=p.timeline.tracks.filter(t=>t.kind==='zoom'&&!t.muted).flatMap(t=>t.clips).filter(c=>activeClip(c,time)).at(-1),view=camera?keyAt(camera,time-camera.start):{scale:1,cx:.5,cy:.5},cx=clamp(view.cx,.5/view.scale,1-.5/view.scale),cy=clamp(view.cy,.5/view.scale,1-.5/view.scale)
  const point=(e:PointerEvent)=>{const r=stage.current!.getBoundingClientRect();return{x:clamp(cx+((e.clientX-r.left)/r.width-.5)/view.scale,0,1),y:clamp(cy+((e.clientY-r.top)/r.height-.5)/view.scale,0,1)}}
  const setKey=(values:Partial<Keyframe>)=>{if(!clip)return;const at=clamp(time-clip.start,0,clipDuration(clip)),key={...keyAt(clip,at),...values,time:at};replace({...clip,keys:[...clip.keys.filter(k=>Math.abs(k.time-at)>16),key].sort((a,b)=>a.time-b.time)})}
  const finishRegion=()=>{region.current=undefined;if(!draft||draft.width<.01||draft.height<.01){setDraft(undefined);return}const scale=clamp(1/Math.max(draft.width,draft.height),1,4),x=draft.x+draft.width/2,y=draft.y+draft.height/2
    if(tool==='region'){if(track?.kind==='zoom'&&clip&&activeClip(clip,time))setKey({scale,cx:x,cy:y});else{const length=Math.min(3000,Math.max(100,duration-time)),c=makeClip(uid(),'区域缩放','',length,time),ramp=Math.min(350,length/4);c.keys=[{time:0,scale:1,cx:.5,cy:.5},{time:ramp,scale,cx:x,cy:y},{time:length-ramp,scale,cx:x,cy:y},{time:length,scale:1,cx:.5,cy:.5}];addClip('zoom',c)}}else if(tool!=='select'){const c=makeClip(uid(),tool==='text'?text:'画面标记','',Math.min(3000,Math.max(100,duration-time)),time);c.mark={id:c.id,tool,color,text,stroke:3,enabled:true,start:0,end:p.duration,x:p.crop.x+draft.x*p.crop.width,y:p.crop.y+draft.y*p.crop.height,width:draft.width*p.crop.width,height:draft.height*p.crop.height};addClip('mark',c)}setDraft(undefined);setTool('select')}
  const beginDrag=(e:PointerEvent,c:TimelineClip,t:TimelineTrack,mode:'move'|'speed'|'trim')=>{if(busy)return;e.stopPropagation();setPlaying(false);setSelected(c.id);drag.current={before:structuredClone(latest.current),clip:structuredClone(c),track:t.id,x:e.clientX,mode};e.currentTarget.setPointerCapture(e.pointerId);setDragging(true)}
  const dragMove=(e:PointerEvent)=>{const d=drag.current;if(!d)return;const delta=(e.clientX-d.x)/px*1000;let c={...d.clip};try{if(d.mode==='move'){let start=Math.max(0,c.start+delta);const edges=d.before.timeline.tracks.flatMap(t=>t.clips).filter(v=>v.id!==c.id).flatMap(v=>[v.start,clipEnd(v)]);const snapped=edges.find(t=>Math.abs(t-start)/1000*px<8);c.start=Math.round((snapped??start)/ (1000/30))*(1000/30)}else if(d.mode==='speed')c=resizeSpeed(c,Math.max(50,clipDuration(c)+delta));else{const change=clamp(delta,-c.in/c.speed,clipDuration(c)-34);c.start+=change;c.in+=change*c.speed;if(c.start<0)return;c.keys=c.keys.filter(k=>k.time>=change).map(k=>({...k,time:k.time-change}))}const next={...d.before,timeline:replaceLinked(d.before.timeline,c)};d.next=next;setP(next)}catch{}}
  const dragEnd=()=>{const d=drag.current;if(d){if(d.next)update(d.next,true,d.before);drag.current=undefined;setDragging(false)}}
  const properties=clip?keyAt(clip,clamp(time-clip.start,0,clipDuration(clip))):undefined
  return <main className="video-editor timeline-editor"><div className="timeline-toolbar"><button disabled={busy} onClick={()=>void work(async()=>onExit?.())}>← 返回 SOP 文档</button><input className="timeline-title" aria-label="项目名称" value={p.title} maxLength={120} onChange={e=>update({...p,title:e.target.value})}/><span>{saved?'已保存':'正在保存…'}</span><button disabled={busy||!undo.current.length} onClick={()=>travel()}>撤销</button><button disabled={busy||!redo.current.length} onClick={()=>travel(true)}>重做</button><select aria-label="导出分辨率" value={height} onChange={e=>setHeight(Number(e.target.value))}><option value={1080}>最高 1080p</option><option value={720}>最高 720p</option><option value={99999}>原始尺寸</option></select><button className="primary" disabled={busy} onClick={()=>void work(async()=>{await window.taVideo.save(p.id,latest.current);await window.taVideo.export(p.id,height)})}>导出 MP4</button></div>
    {busy&&<div className="video-notice">{progress||'正在处理…'}<button onClick={()=>void window.taVideo.cancelExport()}>取消导出</button></div>}
    <div className="timeline-top"><section className="timeline-preview"><div className="timeline-tools"><button onClick={()=>void importMedia('video')} disabled={busy}>添加视频</button><button onClick={()=>void importMedia('audio')} disabled={busy}>添加音频</button>{(['select','region','rect','arrow','highlight','text','cover'] as const).map(t=><button disabled={busy} key={t} className={tool===t?'chosen':''} onClick={()=>setTool(t)}>{({select:'选择',region:'框选放大区域',rect:'矩形',arrow:'箭头',highlight:'高亮',text:'文字',cover:'遮挡'})[t]}</button>)}<input aria-label="标记颜色" type="color" value={color} onChange={e=>setColor(e.target.value)}/>{tool==='text'&&<input aria-label="标记文字" value={text} onChange={e=>setText(e.target.value)} maxLength={500}/>}</div>
      <div className="timeline-stage-wrap"><div className={'timeline-stage '+(tool==='select'?'':'drawing')} ref={stage} style={{aspectRatio:`${p.crop.width}/${p.crop.height}`,'--stage-ratio':p.crop.width/p.crop.height} as CSSProperties} onPointerDown={e=>{if(tool==='select'||busy)return;setPlaying(false);region.current=point(e);setDraft({...region.current,width:0,height:0});e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!region.current)return;const a=region.current,b=point(e);setDraft({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x),height:Math.abs(a.y-b.y)})}} onPointerUp={finishRegion}>
        <div className="timeline-camera" style={{transform:`translate(${(0.5-cx*view.scale)*100}%,${(0.5-cy*view.scale)*100}%) scale(${view.scale})`}}>{p.timeline.tracks.filter(t=>!t.muted&&t.kind!=='zoom').flatMap(t=>t.clips.filter(c=>activeClip(c,time)).map(c=><ClipPreview key={c.id} p={p} clip={c} kind={t.kind} time={time} playing={playing&&!dragging}/>))}{draft&&<div className="timeline-region" style={{left:draft.x*100+'%',top:draft.y*100+'%',width:draft.width*100+'%',height:draft.height*100+'%'}}/>}</div>
      </div></div><div className="timeline-play"><button disabled={busy} onClick={()=>{if(time>=duration)seek(0);setPlaying(!playing)}}>{playing?'暂停':'播放'}</button><button onClick={()=>seek(time-1000/30)}>‹ 一帧</button><span>{clockText(time)} / {clockText(duration)}</span><button onClick={()=>seek(time+1000/30)}>一帧 ›</button><input aria-label="时间线播放位置" type="range" min={0} max={duration} step={1000/30} value={time} onChange={e=>seek(Number(e.target.value))}/><button onClick={()=>void stage.current?.parentElement?.requestFullscreen().catch(e=>onError(e.message))}>全屏预览</button></div>
    </section><aside className="timeline-inspector"><h2>{clip?'选中片段':'片段属性'}</h2>{clip&&track?<><input aria-label="片段名称" value={clip.name} onChange={e=>replace({...clip,name:e.target.value})}/><label>所在轨道<select value={track.id} onChange={e=>update({...p,timeline:{...p.timeline,tracks:p.timeline.tracks.map(t=>({...t,clips:t.id===track.id?t.clips.filter(c=>c.id!==clip.id):t.id===e.target.value?[...t.clips,clip]:t.clips}))}})}>{p.timeline.tracks.filter(t=>t.kind===track.kind).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>开始（秒）<NumberField label="片段开始秒数" value={clip.start/1000} onCommit={n=>replace({...clip,start:Math.max(0,n*1000)})}/></label><label>结束（秒）<NumberField label="片段结束秒数" value={clipEnd(clip)/1000} onCommit={n=>{try{replace(track.kind==='zoom'||track.kind==='mark'?{...clip,out:Math.max(clip.in+34,(n*1000-clip.start)*clip.speed+clip.in),keys:clip.keys.map(k=>({...k,time:k.time*Math.max(34/clip.speed,n*1000-clip.start)/clipDuration(clip)}))}:resizeSpeed(clip,n*1000-clip.start))}catch(e){onError((e as Error).message)}}}/></label><button onClick={()=>replace({...clip,start:time})}>当前帧设为开始</button>
      {(track.kind==='video'||track.kind==='audio')&&<><label>速度<select aria-label="片段速度" value={clip.speed} onChange={e=>replace(resizeSpeed(clip,(clip.out-clip.in)/Number(e.target.value)))}>{[.25,.5,.75,1,1.25,1.5,2,3,4,...(![.25,.5,.75,1,1.25,1.5,2,3,4].includes(clip.speed)?[clip.speed]:[])].map(n=><option key={n} value={n}>{n.toFixed(2)} 倍</option>)}</select></label><label>素材入点（秒）<NumberField label="素材入点" value={clip.in/1000} onCommit={n=>{if(n>=0&&n*1000<clip.out)replace({...clip,in:n*1000,keys:[]})}}/></label><label>素材出点（秒）<NumberField label="素材出点" value={clip.out/1000} onCommit={n=>{const max=p.assets?.find(a=>a.file===clip.asset)?.duration??p.duration;if(n*1000>clip.in&&n*1000<=max)replace({...clip,out:n*1000,keys:clip.keys.filter(k=>k.time<=(n*1000-clip.in)/clip.speed)})}}/></label><label>音量<input aria-label="片段音量" type="range" min={0} max={1} step={.05} value={clip.volume} onChange={e=>replace({...clip,volume:Number(e.target.value)})}/></label></>}
      {(track.kind==='video'||track.kind==='mark')&&<details><summary>画面位置与尺寸（%）</summary>{(['x','y','width','height'] as const).map(k=><label key={k}>{({x:'左',y:'上',width:'宽',height:'高'})[k]}<NumberField label={'画面'+k} value={clip.rect[k]*100} onCommit={n=>replace({...clip,rect:{...clip.rect,[k]:clamp(n/100,k==='x'||k==='y'?0:.02,1)}})}/></label>)}</details>}
      {track.kind!=='audio'&&<><h3>画面缩放关键帧</h3><p>移动播放头，设置该时刻的倍率和中心。两个关键帧间平滑变化。</p><label>倍率<NumberField label="关键帧倍率" value={properties!.scale} onCommit={n=>setKey({scale:clamp(n,1,4)})}/></label><label>中心 X（%）<NumberField label="关键帧中心X" value={properties!.cx*100} onCommit={n=>setKey({cx:clamp(n/100,0,1)})}/></label><label>中心 Y（%）<NumberField label="关键帧中心Y" value={properties!.cy*100} onCommit={n=>setKey({cy:clamp(n/100,0,1)})}/></label><button onClick={()=>setKey({})}>＋ 当前帧关键帧</button>{track.kind==='zoom'&&<button onClick={()=>setTool('region')}>在预览中框选区域</button>}<div className="timeline-key-list">{clip.keys.map((k,i)=><div key={i}><NumberField label={`关键帧 ${i+1} 时间`} value={(clip.start+k.time)/1000} onCommit={n=>{const at=clamp(n*1000-clip.start,0,clipDuration(clip));if(clip.keys.some((v,j)=>j!==i&&Math.abs(v.time-at)<1))return;replace({...clip,keys:clip.keys.map((v,j)=>j===i?{...v,time:at}:v).sort((a,b)=>a.time-b.time)})}}/><button onClick={()=>seek(clip.start+k.time)}>◆ {((clip.start+k.time)/1000).toFixed(2)} 秒 · {k.scale.toFixed(2)}×</button><button aria-label={`删除关键帧 ${i+1}`} onClick={()=>replace({...clip,keys:clip.keys.filter((_,n)=>n!==i)})}>×</button></div>)}</div></>}
      {track.kind==='mark'&&clip.mark&&<><label>标记颜色<input type="color" value={clip.mark.color} onChange={e=>replace({...clip,mark:{...clip.mark!,color:e.target.value}})}/></label><label>文字<input value={clip.mark.text} maxLength={500} onChange={e=>replace({...clip,mark:{...clip.mark!,text:e.target.value}})}/></label></>}
      {clip.link&&<small>已关联原录制声音：时间编辑保持同步。</small>}<label><input type="checkbox" checked={clip.enabled} onChange={e=>replace({...clip,enabled:e.target.checked})}/>预览与导出保留此片段</label><button onClick={remove}>删除选中片段</button></>:<p>点击下方任意片段，调整它的时间、速度、位置和关键帧。新标记默认只保留 3 秒。</p>}</aside></div>
    <section className="timeline-bottom"><div className="timeline-actions"><button disabled={!clip||busy} onClick={split}>当前帧分割</button><button disabled={!clip||busy} onClick={remove}>删除选中片段</button>{(['video','audio','mark','zoom'] as const).map(k=><button disabled={busy} key={k} onClick={()=>addTrack(k)}>＋ {({video:'视频轨',audio:'音频轨',mark:'标记轨',zoom:'缩放轨'})[k]}</button>)}<label>时间线缩放<input type="range" min={5} max={160} value={px} onChange={e=>setPx(Number(e.target.value))}/></label></div><p>拖动片段可移动；左边缘裁切，右边缘拉长/缩短会改变速度。录制的画面与声音联动移动、分割和变速；后添加的视频显示在画面上层。Ctrl+B 分割，Delete 删除，Ctrl+Z 撤销。</p><div className="timeline-scroll"><div className="timeline-content" style={{width:Math.max(800,duration/1000*px+180)}}><div className="timeline-ruler" onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();seek((e.clientX-r.left-140)/px*1000)}}>{Array.from({length:Math.min(400,Math.ceil(duration/1000/5)+1)},(_,i)=><span key={i} style={{left:140+i*5*px}}>{clockText(i*5000)}</span>)}</div>{p.timeline.tracks.map(t=><div className="timeline-track" key={t.id}><div className="timeline-track-label"><span>{t.name}</span><button title="隐藏或静音整轨" onClick={()=>update({...p,timeline:{...p.timeline,tracks:p.timeline.tracks.map(v=>v.id===t.id?{...v,muted:!v.muted}:v)}})}>{t.muted?'关闭':'开启'}</button></div><div className="timeline-track-clips" onPointerDown={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();seek((e.clientX-r.left)/px*1000);setSelected('')}}}>{t.clips.map(c=><div role="button" tabIndex={0} aria-label={t.name+' '+c.name} className={`timeline-clip ${t.kind} ${selected===c.id?'selected':''} ${!c.enabled||t.muted?'disabled':''}`} key={c.id} style={{left:c.start/1000*px,width:Math.max(6,clipDuration(c)/1000*px)}} onPointerDown={e=>beginDrag(e,c,t,'move')} onPointerMove={dragMove} onPointerUp={dragEnd} onDoubleClick={()=>seek(c.start)} onKeyDown={e=>{if(e.key==='Enter'){setSelected(c.id);seek(c.start)}}}><span className="timeline-edge left" onPointerDown={e=>beginDrag(e,c,t,'trim')}/><b>{c.name}</b><small>{c.speed.toFixed(2)}×</small>{c.keys.map((k,i)=><i key={i} style={{left:k.time/1000*px}}>◆</i>)}<span className="timeline-edge right" onPointerDown={e=>beginDrag(e,c,t,'speed')}/></div>)}</div></div>)}<div className="timeline-playhead" style={{left:140+time/1000*px}}/></div></div></section>
  </main>
}
function NumberField({label,value,onCommit}:{label:string;value:number;onCommit:(n:number)=>void}){
  const [draft,setDraft]=useState<string|null>(null),pending=useRef<string|null>(null)
  const commit=()=>{const raw=pending.current;pending.current=null;setDraft(null);if(raw!==null&&raw.trim()&&Number.isFinite(Number(raw))&&Number(raw)!==value)onCommit(Number(raw))}
  return <input aria-label={label} type="number" step={.01} value={draft??Number(value.toFixed(3))} onFocus={()=>{pending.current=String(Number(value.toFixed(3)));setDraft(pending.current)}} onChange={e=>{pending.current=e.target.value;setDraft(e.target.value)}} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){commit();e.currentTarget.blur()}if(e.key==='Escape'){pending.current=null;setDraft(null);e.currentTarget.blur()}}}/>
}
function ClipPreview({p,clip:c,kind,time,playing}:{p:Project;clip:TimelineClip;kind:TrackKind;time:number;playing:boolean}){
  const el=useRef<HTMLVideoElement&HTMLAudioElement>(null),source=clipSourceTime(c,time)/1000,key=keyAt(c,time-c.start),cx=clamp(key.cx,.5/key.scale,1-.5/key.scale),cy=clamp(key.cy,.5/key.scale,1-.5/key.scale)
  const sync=()=>{const v=el.current;if(!v)return;v.playbackRate=c.speed;v.volume=Math.min(1,c.volume);if(v.readyState>=1&&Math.abs(v.currentTime-source)>(playing?.18:.02))v.currentTime=source;if(playing){if(v.paused)void v.play().catch(()=>{})}else v.pause()}
  useEffect(sync,[time,playing,c.speed,c.volume,c.asset]);useEffect(()=>()=>{el.current?.pause()},[])
  if(kind==='audio')return <audio ref={el} src={media(p.id,c.asset)} onLoadedMetadata={sync}/>
  const style={left:c.rect.x*100+'%',top:c.rect.y*100+'%',width:c.rect.width*100+'%',height:c.rect.height*100+'%'}
  return <div className="timeline-layer" style={style}><div className="timeline-layer-transform" style={{transform:`translate(${(0.5-cx*key.scale)*100}%,${(0.5-cy*key.scale)*100}%) scale(${key.scale})`}}>{kind==='mark'?<svg viewBox={`${p.crop.x} ${p.crop.y} ${p.crop.width} ${p.crop.height}`} preserveAspectRatio="none" dangerouslySetInnerHTML={{__html:markSvg(c.mark!)}}/>:<div className="timeline-video-crop"><video ref={el} src={media(p.id,c.asset)} onLoadedMetadata={sync} style={c.asset==='screen.mp4'?{width:p.width/p.crop.width*100+'%',height:p.height/p.crop.height*100+'%',left:-p.crop.x/p.crop.width*100+'%',top:-p.crop.y/p.crop.height*100+'%',objectFit:'fill'}:undefined}/></div>}</div></div>
}
