import { useEffect, useRef, useState, type PointerEvent, type CSSProperties } from 'react'
import { clamp, keepSegments, markSvg, outputAt, outputDuration, previewToSource, sourceAt, tools, viewportAt, visibleMarks, type Mark, type MarkTool, type VideoProject } from '../../../electron/video/model'
import { clockText, media, type ExportProgress } from './bridge'

export function VideoEditor({initial,onError}:{initial:VideoProject;onError:(s:string)=>void}){
  const [p,setP]=useState(initial),latest=useRef(initial),[saved,setSaved]=useState(true),saveTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),queue=useRef(Promise.resolve())
  const dirty=useRef(false); const undo=useRef<VideoProject[]>([]),redo=useRef<VideoProject[]>([])
  const [time,setTime]=useState(0),[playing,setPlaying]=useState(false),[tool,setTool]=useState<MarkTool|'select'>('select'),[selected,setSelected]=useState(''),[draft,setDraft]=useState<Mark>(),[color,setColor]=useState('#FF4D37'),[text,setText]=useState('重点'),[range,setRange]=useState({start:0,end:initial.duration}),[height,setHeight]=useState(1080),[progress,setProgress]=useState<ExportProgress>(),[busy,setBusy]=useState(false),[size,setSize]=useState({w:640,h:360})
  const preview=useRef<HTMLDivElement>(null),video=useRef<HTMLVideoElement>(null),mic=useRef<HTMLAudioElement>(null),system=useRef<HTMLAudioElement>(null),draw=useRef<{x:number;y:number;mark:Mark;move:boolean}|undefined>(undefined),draftRef=useRef<Mark|undefined>(undefined),timeRef=useRef(0)
  const view=viewportAt(p,time),m=p.marks.find(m=>m.id===selected),duration=outputDuration(p)
  const persist=(value:VideoProject)=>{setSaved(false);queue.current=queue.current.catch(()=>{}).then(async()=>{await window.taVideo.save(value.id,value);if(latest.current===value){dirty.current=false;setSaved(true)}}).catch(e=>onError(e.message));return queue.current}
  const change=(next:VideoProject,history=true)=>{if(history){undo.current.push(latest.current);if(undo.current.length>80)undo.current.shift();redo.current=[]}latest.current=next;dirty.current=true;setP(next);setSaved(false);clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>void persist(next),400)}
  const flush=async()=>{clearTimeout(saveTimer.current);await queue.current;await window.taVideo.save(latest.current.id,latest.current);dirty.current=false;setSaved(true)}
  useEffect(()=>window.taVideo.onClosing(()=>{void flush().then(()=>window.taVideo.closeReady()).catch(e=>onError(e.message))}),[])
  useEffect(()=>{const off=window.taVideo.onExport(setProgress);return()=>{off();clearTimeout(saveTimer.current);if(dirty.current)void persist(latest.current)}},[])
  useEffect(()=>{const el=preview.current;if(!el)return;const ro=new ResizeObserver(()=>setSize({w:el.clientWidth,h:el.clientHeight}));ro.observe(el);return()=>ro.disconnect()},[p.crop.width,p.crop.height])
  const syncAudio=(force=false)=>{const v=video.current;if(!v)return;const current=latest.current,muted=current.mutes.some(s=>v.currentTime*1000>=s.start&&v.currentTime*1000<s.end);for(const [el,volume] of [[mic.current,current.micVolume],[system.current,current.systemVolume]] as const){if(!el)continue;el.volume=Math.min(1,volume);el.muted=muted;if(force||Math.abs(el.currentTime-v.currentTime)>.08)el.currentTime=v.currentTime;if(v.paused)el.pause();else if(el.paused)void el.play().catch(()=>{})}}
  const seek=(t:number)=>{if(video.current)video.current.currentTime=t/1000;setTime(t);timeRef.current=t;syncAudio(true)}
  const tick=()=>{const v=video.current;if(!v)return;const t=v.currentTime*1000,current=latest.current,kept=keepSegments(current.duration,current.cuts);if(!v.paused&&!kept.some(s=>t>=s.start&&t<s.end)){const next=kept.find(s=>s.start>t);if(next){seek(next.start);return}v.pause()}setTime(t);timeRef.current=t;syncAudio()}
  useEffect(()=>{if(!playing)return;let id=0;const frame=()=>{tick();id=requestAnimationFrame(frame)};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id)},[playing])
  const updateMark=(changes:Partial<Mark>)=>{if(m)change({...p,marks:p.marks.map(v=>v.id===m.id?{...v,...changes}:v)})}
  const point=(e:PointerEvent)=>{const r=preview.current!.getBoundingClientRect(),v=viewportAt(latest.current,timeRef.current);const pt=previewToSource(v,e.clientX-r.left,e.clientY-r.top,r.width,r.height);return{x:clamp(pt.x,0,p.width),y:clamp(pt.y,0,p.height)}}
  const down=(e:PointerEvent<HTMLDivElement>)=>{if(e.button!==0)return;video.current?.pause();const a=point(e),hit=(e.target as Element).closest('[data-mark]')?.getAttribute('data-mark');if(tool==='select'){if(!hit){setSelected('');return}const mark=p.marks.find(m=>m.id===hit)!;setSelected(hit);draw.current={...a,mark,move:true};draftRef.current=mark;setDraft(mark)}else{const mark:Mark={id:crypto.randomUUID(),tool,color,stroke:3,text:tool==='number'?String(p.marks.filter(m=>m.tool==='number').length+1):text,enabled:true,...a,width:0,height:0,start:Math.min(time,p.duration-1),end:Math.max(Math.min(p.duration,time+3000),Math.min(time,p.duration-1)+1),points:[a]};draw.current={...a,mark,move:false};draftRef.current=mark;setDraft(mark)}e.currentTarget.setPointerCapture(e.pointerId)}
  const move=(e:PointerEvent)=>{const d=draw.current;if(!d)return;const b=point(e),a=d.mark;let next:Mark;if(d.move){const dx=clamp(b.x-d.x,-a.x,p.width-a.x-Math.max(0,a.width)),dy=clamp(b.y-d.y,-a.y,p.height-a.y-Math.max(0,a.height));next={...a,x:a.x+dx,y:a.y+dy,points:a.points?.map(pt=>({...pt,x:pt.x+dx,y:pt.y+dy}))}}else{next={...a,x:a.tool==='arrow'?d.x:Math.min(d.x,b.x),y:a.tool==='arrow'?d.y:Math.min(d.y,b.y),width:a.tool==='arrow'?b.x-d.x:Math.abs(b.x-d.x),height:a.tool==='arrow'?b.y-d.y:Math.abs(b.y-d.y),points:[...(draftRef.current?.points??[]),b]}}draftRef.current=next;setDraft(next)}
  const up=()=>{if(draw.current&&draftRef.current){const mark=draftRef.current;change({...p,marks:draw.current.move?p.marks.map(m=>m.id===mark.id?mark:m):[...p.marks,mark]});setSelected(mark.id)}draw.current=undefined;draftRef.current=undefined;setDraft(undefined)}
  const validRange=()=>{if(range.start<0||range.end>p.duration||range.end-range.start<34){onError('请选择至少一帧的有效时间范围。');return false}return true}
  const cut=()=>{if(!validRange())return;const cuts=[...p.cuts,range];if(!keepSegments(p.duration,cuts).length){onError('至少保留一段视频。');return}change({...p,cuts})}
  const zoom=()=>{if(!validRange())return;const cx=m?m.x+m.width/2:view.x+view.width/2,cy=m?m.y+m.height/2:view.y+view.height/2;change({...p,zooms:[...p.zooms,{id:crypto.randomUUID(),...range,scale:2,cx,cy}]})}
  const runExport=async()=>{setBusy(true);try{clearTimeout(saveTimer.current);await queue.current;await window.taVideo.save(p.id,latest.current);setSaved(true);await window.taVideo.export(p.id,height)}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  return <main className="video-editor"><div className="video-editor-title"><input aria-label="项目名称" value={p.title} maxLength={120} onChange={e=>change({...p,title:e.target.value})}/><span>{saved?'已保存':'保存中…'}</span><button disabled={!undo.current.length||busy} onClick={()=>{const prev=undo.current.pop();if(prev){redo.current.push(p);change(prev,false)}}}>撤销</button><button disabled={!redo.current.length||busy} onClick={()=>{const next=redo.current.pop();if(next){undo.current.push(p);change(next,false)}}}>重做</button><button onClick={()=>void window.taVideo.folder(p.id)}>打开目录</button><select aria-label="导出分辨率" value={height} onChange={e=>setHeight(Number(e.target.value))}><option value={99999}>原始尺寸</option><option value={1080}>最高 1080p</option><option value={720}>最高 720p</option></select><button className="primary" disabled={busy||p.status==='recording'} onClick={()=>void runExport()}>导出 MP4</button></div>
    {p.status==='recovered'&&<p className="video-notice">这是异常结束后保留的项目。请检查可播放范围后再导出。</p>}
    {progress&&<div className="video-export-progress"><progress value={progress.progress} max={1}/><span>{progress.message}</span>{busy&&<button onClick={()=>void window.taVideo.cancelExport()}>取消导出</button>}</div>}
    <div className="video-editor-grid"><section className="video-edit-stage"><nav className="video-tools"><button className={tool==='select'?'chosen':''} onClick={()=>setTool('select')}>选择 / 移动</button>{tools.map(t=><button key={t.id} className={tool===t.id?'chosen':''} onClick={()=>setTool(t.id)}>{t.label}</button>)}<input type="color" aria-label="新标记颜色" value={color} onChange={e=>setColor(e.target.value)}/>{tool==='text'&&<input aria-label="新标记文字" value={text} onChange={e=>setText(e.target.value)}/>}</nav><div className="video-preview-surround"><div ref={preview} className={'video-preview '+(tool!=='select'?'drawing':'')} style={{aspectRatio:`${p.crop.width}/${p.crop.height}`,"--video-ratio":p.crop.width/p.crop.height} as CSSProperties} onPointerDown={down} onPointerMove={move} onPointerUp={up}><div className="video-source-layer" style={{width:p.width,height:p.height,transform:`scale(${size.w/view.width},${size.h/view.height}) translate(${-view.x}px,${-view.y}px)`}}><video ref={video} src={media(p.id,'screen.mp4')} muted playsInline preload="auto" onLoadedMetadata={()=>seek(keepSegments(p.duration,p.cuts)[0]?.start??0)} onTimeUpdate={tick} onSeeked={()=>syncAudio(true)} onPlay={()=>{setPlaying(true);syncAudio(true)}} onPause={()=>{setPlaying(false);syncAudio(true)}} onEnded={()=>setPlaying(false)}/><svg viewBox={`0 0 ${p.width} ${p.height}`} width={p.width} height={p.height}>{visibleMarks(p,time).filter(m=>m.id!==draft?.id).map(mark=><g key={mark.id} data-mark={mark.id} style={{pointerEvents:'all'}} dangerouslySetInnerHTML={{__html:markSvg(mark,time)+(tool==='select'?`<rect x="${mark.x}" y="${mark.y}" width="${Math.max(Math.abs(mark.width),24)}" height="${Math.max(Math.abs(mark.height),24)}" fill="transparent" stroke="${mark.id===selected?'#43E6C1':'none'}" stroke-width="1"/>`:'')}}/>)}{draft&&<g dangerouslySetInnerHTML={{__html:markSvg(draft)}}/>}</svg></div></div></div>
      {p.hasMic&&<audio ref={mic} src={media(p.id,'mic.wav')} preload="auto"/>}{p.hasSystem&&<audio ref={system} src={media(p.id,'system.wav')} preload="auto"/>}
      <div className="video-player-bar"><button onClick={()=>{if(playing)video.current?.pause();else{if(time>=keepSegments(p.duration,p.cuts).at(-1)!.end)seek(keepSegments(p.duration,p.cuts)[0].start);void video.current?.play().catch(e=>onError(e.message))}}}>{playing?'暂停':'播放'}</button><span>{clockText(outputAt(p,time))} / {clockText(duration)}</span><input aria-label="成片播放位置" type="range" min={0} max={duration} step={33.333333} value={outputAt(p,time)} onChange={e=>seek(sourceAt(p,Number(e.target.value)))}/><small>原片 {(time/1000).toFixed(2)} 秒</small></div>
      <section className="video-timeline"><div className="video-row"><b>剪辑范围</b><label>入点 <input aria-label="剪辑入点" type="number" min={0} max={p.duration/1000} step={.1} value={Number((range.start/1000).toFixed(3))} onChange={e=>setRange({...range,start:Number(e.target.value)*1000})}/></label><button onClick={()=>setRange({...range,start:Math.round(time)})}>当前帧设为入点</button><label>出点 <input aria-label="剪辑出点" type="number" min={0} max={p.duration/1000} step={.1} value={Number((range.end/1000).toFixed(3))} onChange={e=>setRange({...range,end:Number(e.target.value)*1000})}/></label><button onClick={()=>setRange({...range,end:Math.round(time)})}>当前帧设为出点</button></div><div className="video-row">{[0,...(p.splits??[]),p.duration].slice(1).map((end,i,ends)=><button key={i} onClick={()=>setRange({start:i?ends[i-1]:0,end})}>片段 {i+1}</button>)}</div><div className="video-source-timeline" title="原片时间线，点击定位" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();seek((e.clientX-r.left)/r.width*p.duration)}}>{p.cuts.map((s,i)=><i className="cut" key={'c'+i} style={{left:`${s.start/p.duration*100}%`,width:`${(s.end-s.start)/p.duration*100}%`}}/>)}{p.zooms.map(z=><i className="zoom" key={z.id} style={{left:`${z.start/p.duration*100}%`,width:`${(z.end-z.start)/p.duration*100}%`}}/>)}<i className="range" style={{left:`${range.start/p.duration*100}%`,width:`${Math.max(0,range.end-range.start)/p.duration*100}%`}}/><i className="playhead" style={{left:`${time/p.duration*100}%`}}/></div><div className="video-row"><button onClick={()=>{if(time>0&&time<p.duration)change({...p,splits:[...new Set([...(p.splits??[]),Math.round(time)])].sort((a,b)=>a-b)})}}>当前帧分割</button><button onClick={cut}>删除选中片段</button><button onClick={()=>{if(validRange())change({...p,cuts:[...(range.start>0?[{start:0,end:range.start}]:[]),...(range.end<p.duration?[{start:range.end,end:p.duration}]:[])]})}}>只保留选中范围</button><button onClick={()=>{if(validRange())change({...p,mutes:[...p.mutes,range]})}}>该段静音</button><button onClick={zoom}>该段放大 2 倍</button></div><p>先选中一个标记，再放大，会以标记位置为中心。删片、静音、放大均可撤销。</p></section>
    </section><aside className="video-inspector"><h3>标记与导出</h3><p>勾选的标记会融合进成片。取消勾选后仍保存在项目中。</p><div className="video-row"><button onClick={()=>change({...p,marks:p.marks.map(m=>({...m,enabled:true}))})}>全选</button><button onClick={()=>change({...p,marks:p.marks.map(m=>m.tool==='cover'?m:{...m,enabled:false})})}>隐藏普通标记</button></div><div className="video-marks">{p.marks.map(mark=><div className={selected===mark.id?'chosen':''} key={mark.id}><input type="checkbox" aria-label={`保留${mark.text||tools.find(t=>t.id===mark.tool)?.label}`} checked={mark.enabled} onChange={e=>change({...p,marks:p.marks.map(m=>m.id===mark.id?{...m,enabled:e.target.checked}:m)})}/><button onClick={()=>{setSelected(mark.id);setTool('select');seek(mark.start)}}><b style={{color:mark.color}}>●</b> {tools.find(t=>t.id===mark.tool)?.label} {mark.tool==='text'||mark.tool==='number'?mark.text:''}<small>{(mark.start/1000).toFixed(1)}–{(mark.end/1000).toFixed(1)} 秒</small></button></div>)}{!p.marks.length&&<p>在画面上拖动以添加标记。</p>}</div>
      {m&&<section className="video-mark-detail"><h4>调整选中标记</h4>{(['start','end'] as const).map(k=><label key={k}>{k==='start'?'出现（秒）':'结束（秒）'}<input type="number" min={0} max={p.duration/1000} step={.1} value={Number((m[k]/1000).toFixed(3))} onChange={e=>updateMark({[k]:Number(e.target.value)*1000})}/></label>)}<div className="video-coordinates">{(['x','y','width','height'] as const).map(k=><label key={k}>{({x:'左',y:'上',width:'宽',height:'高'})[k]}<input type="number" value={Math.round(m[k])} onChange={e=>updateMark({[k]:Number(e.target.value)})}/></label>)}</div>{['text','number'].includes(m.tool)&&<label>文字<input value={m.text} maxLength={500} onChange={e=>updateMark({text:e.target.value})}/></label>}<label>颜色<input type="color" value={m.color} onChange={e=>updateMark({color:e.target.value})}/></label><label>线条 / 字号<input type="range" min={1} max={20} value={m.stroke} onChange={e=>updateMark({stroke:Number(e.target.value)})}/></label><button onClick={()=>{change({...p,marks:p.marks.filter(v=>v.id!==m.id)});setSelected('')}}>移除此标记</button>{m.tool==='cover'&&<p>遮挡只作用于成片；原录像仍保留原始内容。</p>}</section>}
      <h3>画面裁切</h3><div className="video-coordinates">{(['x','y','width','height'] as const).map(k=><label key={k}>{({x:'左',y:'上',width:'宽',height:'高'})[k]}<input type="number" value={p.crop[k]} onChange={e=>{const c={...p.crop,[k]:Number(e.target.value)};if(c.x>=0&&c.y>=0&&c.width>=2&&c.height>=2&&c.x+c.width<=p.width&&c.y+c.height<=p.height)change({...p,crop:c})}}/></label>)}</div><button onClick={()=>change({...p,crop:{x:0,y:0,width:p.width,height:p.height}})}>恢复原始画面</button>
      <h3>声音</h3>{([['micVolume','麦克风',p.hasMic],['systemVolume','电脑声音',p.hasSystem]] as const).map(([key,label,enabled])=><label key={key}>{label} {Math.round(p[key]*100)}%<input disabled={!enabled} type="range" min={0} max={1} step={.05} value={p[key]} onChange={e=>change({...p,[key]:Number(e.target.value)})}/></label>)}
      <h3>片段效果</h3>{p.zooms.map(z=><div className="video-effect" key={z.id}><span>放大 {(z.start/1000).toFixed(1)}–{(z.end/1000).toFixed(1)} 秒</span><select aria-label="放大倍数" value={z.scale} onChange={e=>change({...p,zooms:p.zooms.map(v=>v.id===z.id?{...v,scale:Number(e.target.value)}:v)})}>{[1.5,2,3,4].map(n=><option key={n} value={n}>{n} 倍</option>)}</select><button onClick={()=>change({...p,zooms:p.zooms.filter(v=>v.id!==z.id)})}>移除</button></div>)}{(['cuts','mutes'] as const).map(key=>p[key].map((s,i)=><div className="video-effect" key={key+i}><span>{key==='cuts'?'删片':'静音'} {(s.start/1000).toFixed(1)}–{(s.end/1000).toFixed(1)} 秒</span><button onClick={()=>change({...p,[key]:p[key].filter((_,j)=>j!==i)})}>恢复</button></div>))}
    </aside></div>
  </main>
}
