import { FeishuSettings } from '../sop/FeishuSettings'
import { useEffect, useRef, useState, type PointerEvent } from 'react'
import { clamp, markSvg, tools, type Mark, type MarkTool, type Rect } from '../../../electron/video/model'
import { clockText, media, type RecordingSource, type RecordingState, type VideoProject, type VideoSettings } from './bridge'
import { VideoEditor } from './VideoEditor'
import { SopWorkspace } from '../sop/SopWorkspace'
import '../sop/bridge'
import './video.css'

export function VideoApp(){
  const [list,setList]=useState<VideoProject[]>([]),[project,setProject]=useState<VideoProject>(),[settings,setSettings]=useState<VideoSettings>()
  const [page,setPage]=useState<'library'|'record'|'settings'>('record'),[error,setError]=useState(''),[state,setState]=useState<RecordingState>({phase:'idle',elapsed:0})
  const [videoMode,setVideoMode]=useState(false),[importing,setImporting]=useState(false)
  const refresh=()=>window.taVideo.list().then(setList).catch(e=>setError(e.message))
  useEffect(()=>{if(project)return;return window.taVideo.onClosing(()=>void window.taVideo.closeReady())},[project])
  useEffect(()=>{void window.taVideo.init().then(v=>{setSettings(v.settings);setState(v.state);document.documentElement.dataset.theme=v.theme}).catch(e=>setError(e.message));void refresh();const a=window.taVideo.onState(setState),b=window.taVideo.onFinished(id=>{void window.taVideo.get(id).then(setProject);void refresh()});return()=>{a();b()}},[])
  return <div className="video-shell"><header className="video-header"><strong>拓 Ta <span>录屏与 SOP</span></strong><nav hidden={Boolean(project)}>{(['record','library','settings'] as const).map((p,i)=><button key={p} className={!project&&page===p?'chosen':''} onClick={()=>{setProject(undefined);setPage(p);void refresh()}}>{['新建录屏','视频库','设置'][i]}</button>)}</nav><span className="video-subtle">录制 → SOP → AI 修改</span></header>
    {error&&<div className="video-notice" role="alert">{error}<button onClick={()=>setError('')}>关闭</button></div>}
    {state.phase!=='idle'&&<div className="video-notice">{state.phase==='paused'?'录制已暂停':'正在录制'} {clockText(state.elapsed)}<button onClick={()=>void window.taVideo.stop().catch(e=>setError(e.message))}>停止并整理</button></div>}
    {project?(videoMode?<VideoEditor key={project.id} initial={project} onError={setError} onExit={()=>setVideoMode(false)}/>:<SopWorkspace key={project.id} project={project} onError={setError} onExit={()=>{setProject(undefined);setPage('library');void refresh()}} onVideo={()=>setVideoMode(true)}/>):settings&&page==='record'?<RecordSetup settings={settings} disabled={state.phase!=='idle'} onError={setError}/>:page==='library'?<main className="video-library"><h1>视频库 <small>{list.length} 个项目</small></h1><p>录制或导入视频，生成图文指引，再用 AI 对话完善。</p><button disabled={importing} onClick={()=>{setImporting(true);void window.taSop.importVideo().then(p=>{if(p){setProject(p);setVideoMode(false);void refresh()}}).catch(e=>setError(e.message)).finally(()=>setImporting(false))}}>{importing?'正在导入…':'导入视频生成 SOP'}</button><div className="video-grid">{list.map(p=><button key={p.id} className="video-card" onClick={()=>void window.taVideo.get(p.id).then(setProject).catch(e=>setError(e.message))}><img src={media(p.id,'thumbnail.jpg')} alt="录像预览"/><b>{p.title}</b><span>{clockText(p.duration)} · {p.width} × {p.height}{p.status==='recovered'?' · 已恢复片段':''}</span></button>)}</div>{!list.length&&<p className="video-empty">还没有录像。录完会自动出现在这里。</p>}</main>:settings&&<main className="video-settings"><h1>录屏设置</h1><label>保存目录 <input readOnly value={settings.root}/><button onClick={()=>void window.taVideo.chooseRoot().then(setSettings).catch(e=>setError(e.message))}>更换目录</button></label>{(['startKey','pauseKey','stopKey','annotateKey'] as const).map((k,i)=><label key={k}>{['打开录屏','暂停 / 继续','停止录制','标记 / 操作桌面'][i]}<input value={settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.value})}/></label>)}<label>开始前倒计时<select value={settings.countdown} onChange={e=>setSettings({...settings,countdown:Number(e.target.value)})}><option value={0}>无</option><option value={3}>3 秒</option><option value={5}>5 秒</option></select></label><button className="primary" onClick={()=>void window.taVideo.settings(settings).then(s=>{setSettings(s);setError('录屏设置已保存。')}).catch(e=>setError(e.message))}>保存设置</button><FeishuSettings/></main>}
  </div>
}

function RecordSetup({settings,disabled,onError}:{settings:VideoSettings;disabled:boolean;onError:(s:string)=>void}){
  const [sources,setSources]=useState<RecordingSource[]>([]),[selected,setSelected]=useState(''),[mode,setMode]=useState<'screen'|'region'|'window'>('screen'),[mics,setMics]=useState<string[]>([])
  const [mic,setMic]=useState(settings.mic),[system,setSystem]=useState(settings.system),[micName,setMicName]=useState(settings.micName),[region,setRegion]=useState<Rect>(),[count,setCount]=useState<number|null>(null),[busy,setBusy]=useState(false)
  const cancel=useRef(false),drag=useRef<{x:number;y:number}|undefined>(undefined)
  const [videoMode,setVideoMode]=useState(false),[importing,setImporting]=useState(false)
  const refresh=()=>{setBusy(true);void window.taVideo.sources().then(s=>{setSources(s);setSelected(s.find(s=>s.kind===(mode==='window'?'window':'screen'))?.id??'')}).catch(e=>onError(e.message)).finally(()=>setBusy(false))}
  useEffect(()=>{refresh();void window.taVideo.microphones().then(setMics);return()=>{cancel.current=true}},[])
  const source=sources.find(s=>s.id===selected),width=source?.physical?.width??Math.round((source?.bounds?.width??0)*(source?.scale??1)),height=source?.physical?.height??Math.round((source?.bounds?.height??0)*(source?.scale??1))
  const changeMode=(m:typeof mode)=>{setMode(m);setSelected(sources.find(s=>s.kind===(m==='window'?'window':'screen'))?.id??'');setRegion(undefined)}
  const point=(e:PointerEvent)=>{const r=e.currentTarget.getBoundingClientRect();return{x:Math.round(clamp((e.clientX-r.left)/r.width,0,1)*width),y:Math.round(clamp((e.clientY-r.top)/r.height,0,1)*height)}}
  const start=async()=>{cancel.current=false;setBusy(true);try{for(let n=settings.countdown;n>0;n--){setCount(n);await new Promise(r=>setTimeout(r,1000));if(cancel.current)return}setCount(null);await window.taVideo.start({sourceId:selected,...(mode==='region'?{region}:{}),mic,micName,system})}catch(e){onError(e instanceof Error?e.message:String(e))}finally{setBusy(false);setCount(null)}}
  return <main className="video-setup"><div className="video-heading"><div><h1>录一遍操作，整理成可照做的指引。</h1><p>选择录制范围和声音。录完进入 SOP 工作区，生成步骤、补图并导出文档。</p></div><span className="video-badge">30 FPS · 原始尺寸</span></div><div className="video-row">{(['screen','region','window'] as const).map((m,i)=><button key={m} className={mode===m?'chosen':''} disabled={busy} onClick={()=>changeMode(m)}>{['整个屏幕','指定录制框','单个窗口'][i]}</button>)}<button disabled={busy} onClick={refresh}>刷新来源</button></div><div className="video-source-layout"><div className="video-source-list">{sources.filter(s=>s.kind===(mode==='window'?'window':'screen')).map(s=><button key={s.id} className={selected===s.id?'chosen':''} onClick={()=>{setSelected(s.id);setRegion(undefined)}}><img src={s.thumbnail} alt=""/><span>{s.name}</span></button>)}{!sources.length&&<p>{busy?'正在读取屏幕与窗口…':'没有可用来源'}</p>}</div><section><div className={'video-source-preview '+(mode==='region'?'region':'')} style={{aspectRatio:width&&height?`${width}/${height}`:'16/9'}} onPointerDown={e=>{if(mode!=='region')return;drag.current=point(e);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;const p=point(e),a=drag.current;setRegion({x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),width:Math.abs(a.x-p.x),height:Math.abs(a.y-p.y)})}} onPointerUp={()=>{drag.current=undefined}}>{source&&<img draggable={false} src={source.thumbnail} alt={source.name}/>} {mode==='region'&&region&&<div className="video-region" style={{left:`${region.x/width*100}%`,top:`${region.y/height*100}%`,width:`${region.width/width*100}%`,height:`${region.height/height*100}%`}}/>}</div><p>{mode==='region'?'在预览中拖出录制框，下方可精确调整像素范围。':mode==='window'?'录制选定窗口。录制期间请保持窗口大小与位置稳定。':'录制整个选定显示器。'}</p>{mode==='region'&&region&&<div className="video-row">{(['x','y','width','height'] as const).map(k=><label key={k}>{({x:'左',y:'上',width:'宽',height:'高'})[k]}<input type="number" value={region[k]} min={0} onChange={e=>setRegion({...region,[k]:Number(e.target.value)})}/></label>)}</div>}</section></div><footer className="video-record-footer"><label><input type="checkbox" checked={mic} onChange={e=>setMic(e.target.checked)}/>麦克风</label><select value={micName} disabled={!mic} onChange={e=>setMicName(e.target.value)}><option value="">默认麦克风</option>{mics.map(m=><option key={m}>{m}</option>)}</select><label><input type="checkbox" checked={system} onChange={e=>setSystem(e.target.checked)}/>电脑声音</label><span className="video-subtle">两个音轨分别保存</span><button className="primary" disabled={busy||disabled||!source||(mode==='region'&&(!region||region.width<16||region.height<16))} onClick={()=>void start()}>{count?`${count} 秒后开始`:busy?'正在准备…':'开始录制'}</button>{count!==null&&<button onClick={()=>{cancel.current=true;setCount(null)}}>取消</button>}</footer></main>
}

function useRecording(){const [state,setState]=useState<RecordingState>({phase:'starting',elapsed:0}),[,refresh]=useState(0),received=useRef(Date.now());useEffect(()=>{const receive=(s:RecordingState)=>{received.current=Date.now();setState(s)};void window.taVideo.init().then(v=>receive(v.state));const off=window.taVideo.onState(receive),timer=setInterval(()=>refresh(n=>n+1),100);return()=>{off();clearInterval(timer)}},[]);return {...state,elapsed:state.elapsed+(state.phase==='recording'?Date.now()-received.current:0)}}
export function VideoHud(){const s=useRecording(),[error,setError]=useState('');const act=(p:Promise<unknown>)=>void p.catch(e=>setError(e.message));return <div className="video-hud"><div><b className="record-dot">●</b><strong>{clockText(s.elapsed)}</strong><span>{s.phase==='paused'?'已暂停':s.phase==='starting'?'准备录制':s.phase==='stopping'?'正在保存':'录制中'}</span><button disabled={!['recording','paused'].includes(s.phase)} onClick={()=>act(window.taVideo.pause(s.phase!=='paused'))}>{s.phase==='paused'?'继续':'暂停'}</button><button className={s.drawing?'chosen':''} onClick={()=>act(window.taVideo.ink())}>{s.drawing?'操作桌面':'标记'}</button><button onClick={()=>act(window.taVideo.undoMark())}>撤销</button><button onClick={()=>act(window.taVideo.clear())}>清屏</button><button className="primary" disabled={s.phase==='stopping'} onClick={()=>act(window.taVideo.stop())}>停止并整理</button></div><small>{error||s.message||(s.drawing?'标记模式 · Ctrl+Shift+0 返回操作桌面':'Ctrl+Shift+8 暂停 · Ctrl+Shift+9 停止 · Ctrl+Shift+0 标记')}</small></div>}

export function VideoInk(){const s=useRecording(),[tool,setTool]=useState<MarkTool>('rect'),[color,setColor]=useState('#FF4D37'),[text,setText]=useState('重点'),[draft,setDraft]=useState<Mark>(),[error,setError]=useState(''),start=useRef<{x:number;y:number}|undefined>(undefined);const current=useRef<Mark|undefined>(undefined);const down=(e:PointerEvent<HTMLDivElement>)=>{if(!s.drawing||s.phase!=='recording'||(e.target as HTMLElement).closest('nav'))return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*(s.width??r.width),y=(e.clientY-r.top)/r.height*(s.height??r.height);start.current={x,y};const m:Mark={id:crypto.randomUUID(),tool,color,stroke:3,text:tool==='number'?String((s.marks??[]).filter(m=>m.tool==='number').length+1):text,enabled:true,x,y,width:0,height:0,start:s.elapsed,end:86400000,points:[{x,y,t:s.elapsed}]};current.current=m;setDraft(m);e.currentTarget.setPointerCapture(e.pointerId)};return <div className="video-ink" onPointerDown={down} onPointerMove={e=>{if(!start.current||!current.current)return;const r=e.currentTarget.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width*(s.width??r.width),0,s.width??r.width),y=clamp((e.clientY-r.top)/r.height*(s.height??r.height),0,s.height??r.height),a=start.current,m=current.current;const next={...m,x:tool==='arrow'?a.x:Math.min(a.x,x),y:tool==='arrow'?a.y:Math.min(a.y,y),width:tool==='arrow'?x-a.x:Math.abs(x-a.x),height:tool==='arrow'?y-a.y:Math.abs(y-a.y),points:[...(m.points??[]),{x,y,t:s.elapsed}]};current.current=next;setDraft(next)}} onPointerUp={()=>{const m=current.current;if(m)void window.taVideo.mark(m).catch(e=>setError(e.message));start.current=undefined;current.current=undefined;setDraft(undefined)}}><svg viewBox={`0 0 ${s.width??1} ${s.height??1}`} preserveAspectRatio="none" dangerouslySetInnerHTML={{__html:[...(s.marks??[]).filter(m=>m.end>s.elapsed),...(draft?[draft]:[])].map(m=>markSvg(m)).join('')}}/>{s.drawing&&<nav>{tools.filter(t=>t.id!=='cover').map(t=><button className={tool===t.id?'chosen':''} key={t.id} onClick={()=>setTool(t.id)}>{t.label}</button>)}<input aria-label="标记颜色" type="color" value={color} onChange={e=>setColor(e.target.value)}/>{tool==='text'&&<input aria-label="标记文字" value={text} maxLength={500} onChange={e=>setText(e.target.value)}/>}<button onClick={()=>void window.taVideo.ink()}>返回操作</button>{error&&<small>{error}</small>}</nav>}</div>}
