import {it,expect} from 'vitest'
import {editTimeline,snapMove,snapTime,configureZoom} from './edit-actions'
import {makeClip,keyAt,type Timeline} from './timeline'
import {planEdits} from './cli-engine'
import type {VideoProject} from './model'
const fixture=():Timeline=>({version:1,tracks:[{id:'v',kind:'video',name:'视频',muted:false,clips:[{...makeClip('v1','A','screen.mp4',2000,1000),link:'a'},makeClip('v2','B','screen.mp4',2000,4000)]},{id:'a',kind:'audio',name:'声音',muted:false,clips:[{...makeClip('a1','声音','mic.wav',2000,1000),link:'a'}]},{id:'m',kind:'mark',name:'标记',muted:false,clips:[makeClip('m1','标记','',500,1500)]}]})
let id=0;const uid=()=>String(++id)
it('moves a multi-selection and linked sound together, clamping the group at zero',()=>{const t=fixture(),next=editTimeline(t,{type:'move',ids:['v1','m1'],delta:-2000},uid);expect(next.tracks.map(t=>t.clips.map(c=>c.start))).toEqual([[0,4000],[0],[500]]);expect(t.tracks[0].clips[0].start).toBe(1000)})
it('snaps the nearest selected edge and ignores its linked sound',()=>{const t=fixture();expect(snapMove(t,['v1','m1'],940,0,100)).toEqual({delta:1000,guide:4000});expect(snapTime(t,['v1'],3970,10000,50)).toEqual({time:4000,guide:4000});expect(snapTime(t,['v1'],2970,10000,40).guide).toBeUndefined()})
it('trims source bounds without changing speed, including linked audio',()=>{const t=fixture(),r=editTimeline(t,{type:'trim',id:'v1',side:'left',time:1500,sourceDuration:6000},uid);expect(r.tracks[0].clips[0]).toMatchObject({start:1500,in:500,out:2000,speed:1});expect(r.tracks[1].clips[0]).toMatchObject({start:1500,in:500,out:2000,speed:1});expect(()=>editTimeline(t,{type:'trim',id:'v1',side:'right',time:8000,sourceDuration:6000},uid)).toThrow('素材边界');expect(()=>editTimeline(t,{type:'trim',id:'v1',side:'left',time:2990,sourceDuration:6000},uid)).toThrow('一帧')})
it('splits all selected tracks and ripple deletion preserves unselected overlays',()=>{let t=fixture();t=editTimeline(t,{type:'split',ids:['v1','m1'],time:1750},uid);expect(t.tracks.map(t=>t.clips.length)).toEqual([3,2,2]);expect(()=>editTimeline(fixture(),{type:'delete',ids:['v1'],ripple:true},uid)).toThrow('未选中');const r=editTimeline(fixture(),{type:'delete',ids:['v1','m1'],ripple:true},uid);expect(r.tracks[0].clips[0].start).toBe(2000);expect(r.tracks[1].clips).toHaveLength(0)})

it('makes timed zoom with a held middle and matching linear/hold interpolation',()=>{const c=configureZoom(makeClip('z','Zoom','',4000),{start:1000,end:5000,scale:3,cx:.7,cy:.4,enter:1000,exit:1000,ease:'linear'});expect(keyAt(c,500).scale).toBe(2);expect(keyAt(c,2000).scale).toBe(3);expect(keyAt(c,3500).scale).toBe(2);expect(keyAt(c,4000).scale).toBe(1);c.keys[0].ease='hold';expect(keyAt(c,999).scale).toBe(1);expect(keyAt(c,1000).scale).toBe(3);expect(()=>configureZoom(c,{start:1,end:100,scale:2,cx:.5,cy:.5,enter:200,exit:200})).toThrow()})
it('shares CLI trim and multi-move timing rules with the UI',()=>{const t=fixture();t.tracks=t.tracks.filter(t=>t.kind!=='mark');const p={schemaVersion:1,id:'test',title:'test',micVolume:1,systemVolume:1,cuts:[],mutes:[],zooms:[],marks:[],width:640,height:360,crop:{x:0,y:0,width:640,height:360},duration:6000,hasMic:true,hasSystem:false,timeline:t,assets:[]} as unknown as VideoProject;const r=planEdits(p,[{op:'clip.trim',clipId:'v1',side:'right',time:2500},{op:'clip.move-many',clipIds:['v1','v2'],delta:500}]);expect(r.timeline!.tracks[0].clips[0]).toMatchObject({start:1500,out:1500,speed:1});expect(r.timeline!.tracks[1].clips[0]).toMatchObject({start:1500,out:1500,speed:1})})
