import {describe,it,expect} from 'vitest'
import {migrateTimeline,splitLinked,replaceLinked,removeLinked,resizeSpeed,keyAt,clipDuration,clipSourceTime,validateTimeline,makeClip} from './timeline'
import type {VideoProject} from './model'
const project=():VideoProject=>({schemaVersion:1,id:'1789263021580-e627f35f',title:'test',createdAt:'',revision:0,width:640,height:360,duration:6000,status:'ready',hasMic:true,hasSystem:false,marks:[],cuts:[],mutes:[],zooms:[],crop:{x:0,y:0,width:640,height:360},micVolume:1,systemVolume:1,exports:[]})
describe('tutorial timeline',()=>{
  it('accepts frame-fraction resize rounding while keeping keys within persisted duration',()=>{const p=project();for(let i=0;i<1000;i++){const t=migrateTimeline(p),c=t.tracks[0].clips[0];c.keys=[{time:6000,scale:1,cx:.5,cy:.5}];t.tracks[0].clips[0]=resizeSpeed(c,1500+i/3);const saved=validateTimeline(t,p,[]).tracks[0].clips[0];expect(saved.keys[0].time).toBeLessThanOrEqual(clipDuration(saved))}})
  it('migrates cuts, split points and mute boundaries while linking sound',()=>{const p=project();p.cuts=[{start:1000,end:2000}];p.splits=[4000];p.mutes=[{start:3000,end:3500}];const t=migrateTimeline(p),v=t.tracks[0].clips,a=t.tracks[1].clips;expect(v.map(c=>[c.start,c.in,c.out])).toEqual([[0,0,1000],[1000,2000,3000],[2000,3000,3500],[2500,3500,4000],[3000,4000,6000]]);expect(a.map(c=>c.link)).toEqual(v.map(c=>c.link));expect(a[2].volume).toBe(0);expect(validateTimeline(t,p,[])).toEqual(t)})
  it('moves, resizes, splits and deletes linked recording sound with picture',()=>{let t=migrateTimeline(project()),n=0;t=splitLinked(t,t.tracks[0].clips[0],2000,()=>''+(n++));expect(t.tracks[1].clips).toHaveLength(2);const c=t.tracks[0].clips[1];t=replaceLinked(t,{...resizeSpeed(c,2000),start:3500});const v=t.tracks[0].clips[1],a=t.tracks[1].clips[1];expect([v.start,v.in,v.out,v.speed]).toEqual([a.start,a.in,a.out,a.speed]);expect(clipSourceTime(v,4500)).toBe(4000);t=removeLinked(t,v);expect(t.tracks[0].clips).toHaveLength(1);expect(t.tracks[1].clips).toHaveLength(1)})
  it('keeps keyframes in clip output time through speed changes',()=>{const c=makeClip('a','a','',4000);c.keys=[{time:0,scale:1,cx:.5,cy:.5},{time:4000,scale:3,cx:.75,cy:.25}];expect(keyAt(c,2000)).toEqual({time:2000,scale:2,cx:.625,cy:.375});const fast=resizeSpeed(c,2000);expect(keyAt(fast,1000).scale).toBe(2);expect(clipDuration(fast)).toBe(2000)})
  it('rejects unknown assets, invalid keyframe times and SVG injection',()=>{const p=project(),t=migrateTimeline(p);t.tracks[0].clips[0].asset='../private.mp4';expect(()=>validateTimeline(t,p,[])).toThrow();t.tracks[0].clips[0].asset='screen.mp4';t.tracks[0].clips[0].keys=[{time:7000,scale:2,cx:.5,cy:.5}];expect(()=>validateTimeline(t,p,[])).toThrow();t.tracks[0].clips[0].keys=[];const c=makeClip('bad','bad','',1000);c.mark={id:'x',tool:'rect',color:'red"/><script/>',text:'',stroke:3,x:0,y:0,width:100,height:100,start:0,end:1000,enabled:true};t.tracks.find(t=>t.kind==='mark')!.clips.push(c);expect(()=>validateTimeline(t,p,[])).toThrow('标记参数')})
})
