import { contextBridge, ipcRenderer } from 'electron'

type Listener = (...args: any[]) => void

contextBridge.exposeInMainWorld('taSop', {
  get:(id:string)=>ipcRenderer.invoke('sop:get',id),
  save:(d:unknown)=>ipcRenderer.invoke('sop:save',d),
  generate:(id:string)=>ipcRenderer.invoke('sop:generate',id),
  chat:(id:string,prompt:string,selected:string|undefined,time:number)=>ipcRenderer.invoke('sop:chat',id,prompt,selected,time),
  cancel:(id:string)=>ipcRenderer.invoke('sop:cancel',id),
  frame:(id:string,time:number)=>ipcRenderer.invoke('sop:frame',id,time),
  image:(id:string,paste:boolean)=>ipcRenderer.invoke('sop:image',id,paste),
  transform:(id:string,image:unknown,mode:string,rect:unknown)=>ipcRenderer.invoke('sop:transform',id,image,mode,rect),
  versions:(id:string)=>ipcRenderer.invoke('sop:versions',id),
  restore:(id:string,revision:number)=>ipcRenderer.invoke('sop:restore',id,revision),
  subtitles:(id:string)=>ipcRenderer.invoke('sop:subtitles',id),
  transcribe:(id:string,model:string)=>ipcRenderer.invoke('sop:transcribe',id,model),
  importVideo:()=>ipcRenderer.invoke('sop:import-video'),
  export:(id:string,format:string)=>ipcRenderer.invoke('sop:export',id,format),
  onProgress:(fn:Listener)=>subscribe('sop:progress',fn),
})
contextBridge.exposeInMainWorld('taVideo', {
  open: () => ipcRenderer.invoke('video:open'),
  closeReady: () => ipcRenderer.invoke('video:close-ready'),
  onClosing: (fn: Listener) => subscribe('video:closing', fn),
  init: () => ipcRenderer.invoke('video:init'),
  sources: () => ipcRenderer.invoke('video:sources'),
  microphones: () => ipcRenderer.invoke('video:microphones'),
  list: () => ipcRenderer.invoke('video:list'),
  get: (id: string) => ipcRenderer.invoke('video:get', id),
  save: (id: string, edits: unknown) => ipcRenderer.invoke('video:save', id, edits),
  start: (options: unknown) => ipcRenderer.invoke('video:start', options),
  pause: (paused: boolean) => ipcRenderer.invoke('video:pause', paused),
  stop: () => ipcRenderer.invoke('video:stop'),
  ink: () => ipcRenderer.invoke('video:ink'),
  mark: (mark: unknown) => ipcRenderer.invoke('video:mark', mark),
  clear: () => ipcRenderer.invoke('video:clear'),
  undoMark: () => ipcRenderer.invoke('video:undo-mark'),
  settings: (value: unknown) => ipcRenderer.invoke('video:settings', value),
  chooseRoot: () => ipcRenderer.invoke('video:choose-root'),
  folder: (id?: string) => ipcRenderer.invoke('video:folder', id),
  export: (id: string, height: number) => ipcRenderer.invoke('video:export', id, height),
  cancelExport: () => ipcRenderer.invoke('video:cancel-export'),
  onState: (fn: Listener) => subscribe('video:state', fn),
  onFinished: (fn: Listener) => subscribe('video:finished', fn),
  onExport: (fn: Listener) => subscribe('video:export-progress', fn),
})

function subscribe(channel: string, listener: Listener) {
  const wrapped = (_event: Electron.IpcRendererEvent, ...args: any[]) => listener(...args)
  ipcRenderer.on(channel, wrapped)
  return () => ipcRenderer.removeListener(channel, wrapped)
}

contextBridge.exposeInMainWorld('ta', {
  getAppInfo: () => ipcRenderer.invoke('app:info'),
  windowMinimize: () => ipcRenderer.send('window:minimize'),
  windowToggleMaximize: () => ipcRenderer.send('window:toggle-maximize'),
  windowClose: () => ipcRenderer.send('window:close'),
  startCapture: (action: string) => ipcRenderer.invoke('capture:start', action),
  cancelCapture: () => ipcRenderer.send('overlay:cancel'),
  getOverlayInit: () => ipcRenderer.invoke('overlay:get-init'),
  getLongCaptureProgress: () => ipcRenderer.invoke('long-capture:get-progress'),
  reportOverlayReady: () => ipcRenderer.send('overlay:ready'),
  submitSelection: (rect: unknown) => ipcRenderer.send('overlay:select', rect),
  getResult: () => ipcRenderer.invoke('result:get'),
  copyImage: (dataUrl?: string) => ipcRenderer.invoke('image:copy', dataUrl),
  copyText: (value: string) => ipcRenderer.invoke('text:copy', value),
  saveImage: (dataUrl?: string) => ipcRenderer.invoke('image:save', dataUrl),
  showImageContextMenu: (request: unknown) => ipcRenderer.invoke('image:context-menu', request),
  pinImage: (dataUrl?: string) => ipcRenderer.invoke('image:pin', dataUrl),
  commitImage: (dataUrl: string, action: string) => ipcRenderer.invoke('image:commit', dataUrl, action),
  runOCR: (dataUrl?: string) => ipcRenderer.invoke('ocr:run', dataUrl),
  runAI: (mode: string, dataUrl?: string, prompt?: string) => ipcRenderer.invoke('ai:run', mode, dataUrl, prompt),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (settings: unknown) => ipcRenderer.invoke('settings:save', settings),
  setHotkeyRecording: (active: boolean) => ipcRenderer.send('hotkeys:recording', active),
  getHistory: () => ipcRenderer.invoke('history:list'),
  listAssets: (query?: unknown) => ipcRenderer.invoke('library:list', query),
  getLibraryStats: () => ipcRenderer.invoke('library:stats'),
  retryLegacyMigration: () => ipcRenderer.invoke('library:retry-migration'),
  chooseStorageRoot: () => ipcRenderer.invoke('library:choose-root'),
  openStorageRoot: () => ipcRenderer.invoke('library:open-root'),
  pasteClipboardImage: () => ipcRenderer.invoke('library:paste'),
  importImages: () => ipcRenderer.invoke('library:import'),
  renameAsset: (id: string, title: string) => ipcRenderer.invoke('library:rename', id, title),
  deleteAssets: (ids: string[]) => ipcRenderer.invoke('library:delete-many', ids),
  exportAssets: (selection: unknown) => ipcRenderer.invoke('library:export', selection),
  openHistory: (id: string) => ipcRenderer.invoke('history:open', id),
  deleteHistory: (id: string) => ipcRenderer.invoke('history:delete', id),
  showMain: () => ipcRenderer.send('navigation:home'),
  openSettings: () => ipcRenderer.send('navigation:settings'),
  pinCommand: (command: string, value?: number) => ipcRenderer.send('pin:command', command, value),
  getPinInit: () => ipcRenderer.invoke('pin:get-init'),
  onOverlayInit: (listener: Listener) => subscribe('overlay:init', listener),
  onLongCaptureProgress: (listener: Listener) => subscribe('long-capture:progress', listener),
  onPinInit: (listener: Listener) => subscribe('pin:init', listener),
  onHotkeyStatus: (listener: Listener) => subscribe('hotkeys:status', listener),
  onNavigate: (listener: Listener) => subscribe('navigation:route', listener),
  onHistoryChanged: (listener: Listener) => subscribe('history:changed', listener),
  onLibraryChanged: (listener: Listener) => subscribe('library:changed', listener),
})
